name: BUILD
on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master, staging ]
  workflow_dispatch:

jobs:
  test:
    name: Test and build
    runs-on: macos-latest

    steps:
    - name: Use Node.js
      uses: actions/checkout@v2
        
    - name: npm install test and lint
      run: |
        echo "===========INSTALLING============"
        npm install
        echo "======PATCHING DEPENDENCIES======"
        npm run postinstall
        echo "=============TESTING============="
        npm run test:unit
        echo "=============LINTING============="
        npm run lint:script
        echo "=============BUILDING============="
        npm run build
