name: BUILD
on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master, staging ]
  workflow_dispatch:

jobs:
  test:
    name: Test and build
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v3.0.0
      
    - name: Say Hi
      run: |
        echo "Installing"
        ls
        ls ../
        
    - name: npm install and test
      run: |
        npm install
        npm run test:unit
      working-directory: ./valorize_frontend
