name: BUILD
on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master, staging ]
  workflow_dispatch:

jobs:
  test:
    name: Test and build
    runs-on: macos-latest

    steps:
    - name: Use Node.js
      uses: actions/checkout@v2
        
    - name: npm install test and lint
      run: |
        npm install
        npm run test:unit
        npm run lint:script
        npm run build
